version: '3'
services:
  flask:
    build: .
    container_name: flask-test
    environment:
      - PYTHONUNBUFFERED=True
    restart: on-failure
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    command: flask run